/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Servicios;

import controlador.ControladorPrincipal;
import javax.swing.JOptionPane;
import vista.frmPrincipal;

/**
 *
 * @author juanm
 */
public class jdialogPagoServicios extends javax.swing.JDialog {

    ControladorPrincipal cp;
    frmPrincipal vp;
    
    /**
     * Creates new form jdialogPagoServicios
     */
    public jdialogPagoServicios(java.awt.Frame parent, boolean modal, ControladorPrincipal cp,frmPrincipal vp) {
        super(parent, modal);
        initComponents();
        this.cp = cp;
        this.vp = vp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPagos = new javax.swing.JPanel();
        pnlBuscarPagos = new javax.swing.JPanel();
        rdbMes = new javax.swing.JRadioButton();
        mcrMes = new com.toedter.calendar.JMonthChooser();
        ycrAnio = new com.toedter.calendar.JYearChooser();
        rdbAnio = new javax.swing.JRadioButton();
        btnBuscarCiclo = new javax.swing.JButton();
        btnTodosCliente1 = new javax.swing.JButton();
        scpPagosServicios = new javax.swing.JScrollPane();
        tblPagoServicios = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnNuevoPago = new javax.swing.JButton();
        pnlNuevoPago = new javax.swing.JPanel();
        lblServicio = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        lblComentario = new javax.swing.JLabel();
        scpComentario = new javax.swing.JScrollPane();
        txaComentario = new javax.swing.JTextArea();
        lblCosto = new javax.swing.JLabel();
        lblMoneda = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        dtcFecha = new com.toedter.calendar.JDateChooser();
        btnRegistrarPago = new javax.swing.JButton();
        scpServicios = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnTodosCliente = new javax.swing.JButton();
        btnAgregarServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPagos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 16))); // NOI18N

        pnlBuscarPagos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 16))); // NOI18N

        rdbMes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdbMes.setText("Por Mes");
        rdbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMesActionPerformed(evt);
            }
        });

        mcrMes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        rdbAnio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdbAnio.setText("Por Año");
        rdbAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAnioActionPerformed(evt);
            }
        });

        btnBuscarCiclo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBuscarCiclo.setText("Buscar");
        btnBuscarCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCicloActionPerformed(evt);
            }
        });

        btnTodosCliente1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnTodosCliente1.setText("Todos");
        btnTodosCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosCliente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarPagosLayout = new javax.swing.GroupLayout(pnlBuscarPagos);
        pnlBuscarPagos.setLayout(pnlBuscarPagosLayout);
        pnlBuscarPagosLayout.setHorizontalGroup(
            pnlBuscarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mcrMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbMes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBuscarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ycrAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbAnio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTodosCliente1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBuscarPagosLayout.setVerticalGroup(
            pnlBuscarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBuscarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarCiclo)
                        .addComponent(btnTodosCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBuscarPagosLayout.createSequentialGroup()
                        .addGroup(pnlBuscarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBuscarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mcrMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ycrAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblPagoServicios = new javax.swing.JTable(){
            public boolean isCellEditable(int r, int c){
                return false;
            }
        };
        tblPagoServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tblPagoServicios.getTableHeader().setReorderingAllowed(false);
        tblPagoServicios.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblPagoServiciosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblPagoServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPagoServiciosMouseClicked(evt);
            }
        });
        scpPagosServicios.setViewportView(tblPagoServicios);

        btnModificar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnNuevoPago.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnNuevoPago.setText("Nuevo");
        btnNuevoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPagosLayout = new javax.swing.GroupLayout(pnlPagos);
        pnlPagos.setLayout(pnlPagosLayout);
        pnlPagosLayout.setHorizontalGroup(
            pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPagosLayout.createSequentialGroup()
                        .addComponent(btnNuevoPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlBuscarPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scpPagosServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPagosLayout.setVerticalGroup(
            pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBuscarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpPagosServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        pnlNuevoPago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 16))); // NOI18N

        lblServicio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblServicio.setText("Servicio");

        txtServicio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtServicio.setEnabled(false);
        txtServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicioActionPerformed(evt);
            }
        });

        lblComentario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblComentario.setText("Comentario");

        txaComentario.setColumns(10);
        txaComentario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txaComentario.setLineWrap(true);
        txaComentario.setRows(5);
        txaComentario.setMaximumSize(new java.awt.Dimension(500, 2147483647));
        scpComentario.setViewportView(txaComentario);

        lblCosto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCosto.setText("Costo*");

        lblMoneda.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblMoneda.setText("$");

        txtCosto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblFecha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblFecha.setText("Fecha");

        btnRegistrarPago.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnRegistrarPago.setText("Registrar Pago");
        btnRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagoActionPerformed(evt);
            }
        });

        tblServicios = new javax.swing.JTable(){
            public boolean isCellEditable(int r, int c){
                return false;
            }
        };
        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tblServicios.getTableHeader().setReorderingAllowed(false);
        tblServicios.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblServiciosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiciosMouseClicked(evt);
            }
        });
        scpServicios.setViewportView(tblServicios);

        txtBuscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnTodosCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnTodosCliente.setText("Todos");
        btnTodosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosClienteActionPerformed(evt);
            }
        });

        btnAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNuevoPagoLayout = new javax.swing.GroupLayout(pnlNuevoPago);
        pnlNuevoPago.setLayout(pnlNuevoPagoLayout);
        pnlNuevoPagoLayout.setHorizontalGroup(
            pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlNuevoPagoLayout.createSequentialGroup()
                        .addGroup(pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scpComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComentario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuevoPagoLayout.createSequentialGroup()
                                .addGroup(pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFecha)
                                    .addComponent(lblCosto))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlNuevoPagoLayout.createSequentialGroup()
                                .addComponent(lblMoneda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCosto))
                            .addComponent(dtcFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlNuevoPagoLayout.createSequentialGroup()
                        .addGroup(pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuevoPagoLayout.createSequentialGroup()
                                .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scpServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlNuevoPagoLayout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTodosCliente))
                            .addComponent(lblServicio))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlNuevoPagoLayout.setVerticalGroup(
            pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTodosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpServicios, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblServicio)
                        .addGroup(pnlNuevoPagoLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAgregarServicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoPagoLayout.createSequentialGroup()
                        .addComponent(lblCosto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlNuevoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMoneda)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNuevoPagoLayout.createSequentialGroup()
                        .addComponent(lblComentario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scpComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlNuevoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNuevoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMesActionPerformed
        dtcFecha.setEnabled(false);
        mcrMes.setEnabled(true);
        ycrAnio.setEnabled(true);
    }//GEN-LAST:event_rdbMesActionPerformed

    private void rdbAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAnioActionPerformed
        dtcFecha.setEnabled(false);
        mcrMes.setEnabled(false);
        ycrAnio.setEnabled(true);
    }//GEN-LAST:event_rdbAnioActionPerformed

    private void btnBuscarCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCicloActionPerformed

        if (rdbMes.isSelected()) {
            String mes = String.valueOf(mcrMes.getMonth() + 1);
            String anio = String.valueOf(ycrAnio.getYear());

            if (mcrMes.getMonth() < 10) {
                mes = "0" + String.valueOf(mes);
            }
            String fechaBusqueda = anio + "-" + mes;

            //            UtilVista.cargarTablaPagoServicio(cp.getCs().traerPagosServiciosPorMes(fechaBusqueda), tblPagoServicios);

        } else if (rdbAnio.isSelected()) {
            String anio = String.valueOf(ycrAnio.getYear());

            //     UtilVista.cargarTablaPagoServicio(cp.getCs().traerPagosServiciosPorAnio(anio), tblPagoServicios);

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una tipo de búsqueda");
        }
    }//GEN-LAST:event_btnBuscarCicloActionPerformed

    private void btnTodosCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosCliente1ActionPerformed
        //        UtilVista.cargarTablaPagoServicio(cp.getCs().traerPagosServicios(), tblPagoServicios);
        //estadoInicial();
    }//GEN-LAST:event_btnTodosCliente1ActionPerformed

    private void tblPagoServiciosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblPagoServiciosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPagoServiciosAncestorAdded

    private void tblPagoServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPagoServiciosMouseClicked
        if (tblPagoServicios.getSelectedRow() > -1 && tblPagoServicios.getSelectedRowCount() == 1) {
            int seleccionado = (int) tblPagoServicios.getValueAt(tblPagoServicios.getSelectedRow(), 0);
            /*
            PagoDeServicio pago = cp.getCs().traerPagoServicio(seleccionado);

            txtServicio.setText(pago.getServicio().getNombre());
            int costo = (int) pago.getImporte();
            txtCosto.setText(String.valueOf(costo));
            txaComentario.setText(pago.getComentario());
            dtcFecha.setDate(pago.getFecha());

            bloquearCampos();
            habilitarBotones();
            */
        }
    }//GEN-LAST:event_tblPagoServiciosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
//       opcion = "modificar";
        btnRegistrarPago.setEnabled(true);
        //tblServicios.setEnabled(false);
 //       habilitarCampos();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        try {
            if (tblPagoServicios.getSelectedRow() > -1 && tblPagoServicios.getSelectedRowCount() == 1) {
                int seleccionado = (int) tblPagoServicios.getValueAt(tblPagoServicios.getSelectedRow(), 0);
                int seleccion = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro que desea elimar este Pago de Servicio?", "input", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (seleccion == JOptionPane.YES_OPTION) {

                    JOptionPane.showMessageDialog(rootPane, "El Pago de Servicio se eliminó exitosamente");
                    //                    cp.getCs().borrarPagoServicio(seleccionado);
//                    estadoInicial();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Seleccione un elemento de la Tabla");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnNuevoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPagoActionPerformed
       /*
        opcion = "nuevo";
        limpiarCampos();
        habilitarCampos();
       */
        tblServicios.setEnabled(true);
        btnRegistrarPago.setEnabled(true);
    }//GEN-LAST:event_btnNuevoPagoActionPerformed

    private void txtServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicioActionPerformed

    private void btnRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagoActionPerformed
       /*
        if (opcion.equals("nuevo")) {
            if (txtServicio.getText().isEmpty() || txtCosto.getText().isEmpty() || dtcFecha.getCalendar().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Seleccione un servicio y/o complete los campos obligatorios");
            } else {
                
                try {
                    Taller taller = cp.getCl().traerTaller(1);
                    Servicio servicio = cp.getCs().traerServicioPorNombre(txtServicio.getText());
                    double costo = Double.parseDouble(txtCosto.getText());
                    Date fecha = dtcFecha.getDate();
                    String comentario = txaComentario.getText();

                    cp.getCs().nuevoPagoDeServicio(costo, fecha, comentario, taller, servicio);
                    JOptionPane.showMessageDialog(rootPane, "El Pago de Servicio se registró con éxito");
                    estadoInicial();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
                
            }
        } else if (opcion.equals("modificar")) {
            if (txtServicio.getText().isEmpty() || txtCosto.getText().isEmpty() || dtcFecha.getCalendar().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Complete los campos obligatorios");
            } else {
                try {
                    if (tblPagoServicios.getSelectedRow() > -1 && tblPagoServicios.getSelectedRowCount() == 1) {
                        int seleccionado = (int) tblPagoServicios.getValueAt(tblPagoServicios.getSelectedRow(), 0);
                        double costo = Double.parseDouble(txtCosto.getText());
                        Date fecha = dtcFecha.getDate();
                        String comentario = txaComentario.getText();

                        //   cp.getCs().editarPagoDeServicio(seleccionado, costo, fecha, comentario);
                        JOptionPane.showMessageDialog(rootPane, "El Pago de Servicio se modificó con éxito");
                        estadoInicial();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }
        }
        */
    }//GEN-LAST:event_btnRegistrarPagoActionPerformed

    private void tblServiciosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblServiciosAncestorAdded

    }//GEN-LAST:event_tblServiciosAncestorAdded

    private void tblServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiciosMouseClicked
        if (tblServicios.getSelectedRow() > -1 && tblServicios.getSelectedRowCount() == 1) {
            int seleccionado = (int) tblServicios.getValueAt(tblServicios.getSelectedRow(), 0);
            //            Servicio servicio = cp.getCs().traerServicio(seleccionado);

            //          UtilVista.cargarTablaPagoServicio(cp.getCs().traerPagosServiciosPorTipo(servicio.getNombre()), tblPagoServicios);
            //        txtServicio.setText(servicio.getNombre());
//            limpiarDatos();
        }
    }//GEN-LAST:event_tblServiciosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
 //       limpiarCampos();
        if (txtBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "No hay parámetro de búsqueda");
            txtBuscar.requestFocus();
        } else {
            if (txtBuscar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "No hay parametro de busqueda");
                txtBuscar.requestFocus();
            } else {
                // UtilVista.cargarTablaServicios(cp.getCs().buscarServicioPorNombre(txtBuscar.getText()), tblServicios);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnTodosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosClienteActionPerformed
    //    limpiarCampos();
        //  UtilVista.cargarTablaServicios(cp.getCs().traerServicios(), tblServicios);
    }//GEN-LAST:event_btnTodosClienteActionPerformed

    private void btnAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioActionPerformed
       jdialogServicios serv = new jdialogServicios(vp, true, cp, this, true);
       serv.show();
    }//GEN-LAST:event_btnAgregarServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarServicio;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarCiclo;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevoPago;
    private javax.swing.JButton btnRegistrarPago;
    private javax.swing.JButton btnTodosCliente;
    private javax.swing.JButton btnTodosCliente1;
    private com.toedter.calendar.JDateChooser dtcFecha;
    private javax.swing.JLabel lblComentario;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMoneda;
    private javax.swing.JLabel lblServicio;
    private com.toedter.calendar.JMonthChooser mcrMes;
    private javax.swing.JPanel pnlBuscarPagos;
    private javax.swing.JPanel pnlNuevoPago;
    private javax.swing.JPanel pnlPagos;
    private javax.swing.JRadioButton rdbAnio;
    private javax.swing.JRadioButton rdbMes;
    private javax.swing.JScrollPane scpComentario;
    private javax.swing.JScrollPane scpPagosServicios;
    private javax.swing.JScrollPane scpServicios;
    private javax.swing.JTable tblPagoServicios;
    public javax.swing.JTable tblServicios;
    private javax.swing.JTextArea txaComentario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtServicio;
    private com.toedter.calendar.JYearChooser ycrAnio;
    // End of variables declaration//GEN-END:variables
}
