/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Pedido;

import controlador.ControladorPrincipal;
import javax.swing.JOptionPane;
import vista.Pagos.jdialogMetodoPago;
import vista.UtilVista;
import vista.frmPrincipal;

/**
 *
 * @author juanm
 */
public class ifrmPedido extends javax.swing.JInternalFrame {

    ControladorPrincipal cp;
    frmPrincipal vp;
    double cuotas;

    /**
     * Creates new form ifrmPago
     */
    public ifrmPedido(ControladorPrincipal cp, frmPrincipal vp) {
        initComponents();
        this.cp = cp;
        this.vp = vp;
        initState();
    }

    public void initState() {
        UtilVista.cargarTablaCliente(cp.getCc().findAllClienteBaja(false), tblClientes);
        BlockTxt();
    }

    public void BlockTxt() {
        txtMaquinas.setEnabled(false);
        txtColor.setEnabled(false);
        
        spnCantidad.setEnabled(false);
        
        txtSenia.setEnabled(false);
    }

    public void UnBlockTxt() {
        txtCliente.setEnabled(true);
        txtMaquinas.setEnabled(true);
        spnCantidad.setEnabled(true);
        txtCostoUnidad.setEnabled(true);
        tblPedidos.setEnabled(true);

        cmbEstado.setEnabled(true);
        cmbCuotas.setEnabled(true);
        cmbMetodoPago.setEnabled(true);

        dtcFecha.setEnabled(true);

        txtInteres.setEnabled(true);
        txtDescuento.setEnabled(true);
        txtSenia.setEnabled(true);
    }

    public void blockButtons() {
        btnAgregarM.setEnabled(false);
        btnModifM.setEnabled(false);
        btnEliminarM.setEnabled(false);
        btnAgregarMetodo.setEnabled(false);
        btnCalcularTotal.setEnabled(false);
        btnGuardarPedido.setEnabled(false);
    }

    public void unBlockButtons() {
        btnAgregarM.setEnabled(true);
        btnModifM.setEnabled(true);
        btnEliminarM.setEnabled(true);
        btnAgregarMetodo.setEnabled(true);
        btnCalcularTotal.setEnabled(true);
        btnGuardarPedido.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbgCliente = new javax.swing.ButtonGroup();
        rdbgMaquina = new javax.swing.ButtonGroup();
        pnlClientes = new javax.swing.JPanel();
        rdbApellido = new javax.swing.JRadioButton();
        rdbDni = new javax.swing.JRadioButton();
        rdbCelular = new javax.swing.JRadioButton();
        txtBuscarC = new javax.swing.JTextField();
        btnBuscarC = new javax.swing.JButton();
        btnTodosCliente = new javax.swing.JButton();
        scpClientes = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txtCliente = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        pnlMaquinas = new javax.swing.JPanel();
        scpMaquinas = new javax.swing.JScrollPane();
        tblMaquinas = new javax.swing.JTable();
        rdbNombre = new javax.swing.JRadioButton();
        rdbCOD = new javax.swing.JRadioButton();
        txtBuscarM = new javax.swing.JTextField();
        btnBuscarM = new javax.swing.JButton();
        btnTodasMaquinas = new javax.swing.JButton();
        pnlPedido = new javax.swing.JPanel();
        lblCantidad = new javax.swing.JLabel();
        lblMaquinas = new javax.swing.JLabel();
        txtMaquinas = new javax.swing.JTextField();
        spnCantidad = new javax.swing.JSpinner();
        txtCostoUnidad = new javax.swing.JTextField();
        lblCostoUnidad = new javax.swing.JLabel();
        lblImporteM = new javax.swing.JLabel();
        lblDetalles = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        lblMoney = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        btnAgregarM = new javax.swing.JButton();
        btnModifM = new javax.swing.JButton();
        btnEliminarM = new javax.swing.JButton();
        lblMetodoPago = new javax.swing.JLabel();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        lblEstadoPago = new javax.swing.JLabel();
        btnAgregarMetodo = new javax.swing.JButton();
        lblCuotas = new javax.swing.JLabel();
        cmbCuotas = new javax.swing.JComboBox<>();
        dtcFecha = new com.toedter.calendar.JDateChooser();
        lblFecha = new javax.swing.JLabel();
        lblInteres = new javax.swing.JLabel();
        lblIPorcentaje = new javax.swing.JLabel();
        txtInteres = new javax.swing.JTextField();
        lblSenia = new javax.swing.JLabel();
        txtSenia = new javax.swing.JTextField();
        btnCalcularTotal = new javax.swing.JButton();
        lblDescuento = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        lblMontoCuota = new javax.swing.JLabel();
        lblMoneyCuota = new javax.swing.JLabel();
        txtMontoCuota = new javax.swing.JTextField();
        txtMontoTotal = new javax.swing.JTextField();
        lblMoneyTotal = new javax.swing.JLabel();
        lblMontoTotal = new javax.swing.JLabel();
        btnGuardarPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        scpPedidos = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();

        pnlClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N
        pnlClientes.setOpaque(false);

        rdbApellido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdbApellido.setText("Apellido");
        rdbApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbApellidoMouseClicked(evt);
            }
        });
        rdbApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbApellidoActionPerformed(evt);
            }
        });

        rdbDni.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdbDni.setText("DNI");
        rdbDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbDniMouseClicked(evt);
            }
        });
        rdbDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDniActionPerformed(evt);
            }
        });

        rdbCelular.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdbCelular.setText("Celular");
        rdbCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbCelularMouseClicked(evt);
            }
        });
        rdbCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCelularActionPerformed(evt);
            }
        });

        txtBuscarC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtBuscarC.setEnabled(false);
        txtBuscarC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCKeyTyped(evt);
            }
        });

        btnBuscarC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBuscarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_search_16px.png"))); // NOI18N
        btnBuscarC.setText("Buscar");
        btnBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCActionPerformed(evt);
            }
        });

        btnTodosCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnTodosCliente.setText("Todos");
        btnTodosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosClienteActionPerformed(evt);
            }
        });

        tblClientes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "DNI", "Celular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpClientes.setViewportView(tblClientes);

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCliente.setEnabled(false);
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        lblCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCliente.setText("Cliente");

        lblDni.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblDni.setText("DNI");

        txtDni.setEditable(false);
        txtDni.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtDni.setEnabled(false);
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpClientes)
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addComponent(rdbApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnTodosCliente))
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente)
                            .addComponent(txtCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDni)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTodosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdbApellido)
                        .addComponent(rdbDni)
                        .addComponent(txtBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdbCelular)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlClientesLayout.createSequentialGroup()
                            .addComponent(lblCliente)
                            .addGap(28, 28, 28))
                        .addComponent(txtCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addComponent(lblDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlMaquinas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N
        pnlMaquinas.setOpaque(false);

        tblMaquinas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblMaquinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpMaquinas.setViewportView(tblMaquinas);

        rdbNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdbNombre.setText("Nombre");
        rdbNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbNombreMouseClicked(evt);
            }
        });
        rdbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNombreActionPerformed(evt);
            }
        });

        rdbCOD.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdbCOD.setText("COD");
        rdbCOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbCODMouseClicked(evt);
            }
        });
        rdbCOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCODActionPerformed(evt);
            }
        });

        txtBuscarM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtBuscarM.setEnabled(false);
        txtBuscarM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarMKeyTyped(evt);
            }
        });

        btnBuscarM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBuscarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_search_16px.png"))); // NOI18N
        btnBuscarM.setText("Buscar");
        btnBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMActionPerformed(evt);
            }
        });

        btnTodasMaquinas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnTodasMaquinas.setText("Todos");
        btnTodasMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodasMaquinasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMaquinasLayout = new javax.swing.GroupLayout(pnlMaquinas);
        pnlMaquinas.setLayout(pnlMaquinasLayout);
        pnlMaquinasLayout.setHorizontalGroup(
            pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaquinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpMaquinas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMaquinasLayout.createSequentialGroup()
                        .addComponent(rdbNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbCOD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btnBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnTodasMaquinas)))
                .addContainerGap())
        );
        pnlMaquinasLayout.setVerticalGroup(
            pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaquinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTodasMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdbNombre)
                        .addComponent(rdbCOD)
                        .addComponent(txtBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N
        pnlPedido.setOpaque(false);

        lblCantidad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCantidad.setText("Cantidad");

        lblMaquinas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblMaquinas.setText("Máquina");

        txtMaquinas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtMaquinas.setEnabled(false);
        txtMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaquinasActionPerformed(evt);
            }
        });

        spnCantidad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtCostoUnidad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCostoUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoUnidadKeyTyped(evt);
            }
        });

        lblCostoUnidad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCostoUnidad.setText("c/u: $");

        lblImporteM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblImporteM.setText("Importe");

        lblDetalles.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblDetalles.setText("Detalles del pedido");

        lblSubTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblSubTotal.setText("SubTotal:");

        lblMoney.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblMoney.setText("$");

        txtSubTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtSubTotal.setEnabled(false);
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        btnAgregarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_plus_math_16px.png"))); // NOI18N
        btnAgregarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMActionPerformed(evt);
            }
        });

        btnModifM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_edit_16px.png"))); // NOI18N
        btnModifM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifMActionPerformed(evt);
            }
        });

        btnEliminarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_trash_16px.png"))); // NOI18N
        btnEliminarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMActionPerformed(evt);
            }
        });

        lblMetodoPago.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblMetodoPago.setText("Método de Pago");

        cmbMetodoPago.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[SELECCIONAR]" }));
        cmbMetodoPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbMetodoPagoMouseClicked(evt);
            }
        });
        cmbMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMetodoPagoActionPerformed(evt);
            }
        });

        cmbEstado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[SELECCIONAR]", "Pendiente", "Pagado" }));
        cmbEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbEstadoMouseClicked(evt);
            }
        });
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        lblEstadoPago.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblEstadoPago.setText("Estado del Pago");

        btnAgregarMetodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_add_16px.png"))); // NOI18N
        btnAgregarMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMetodoActionPerformed(evt);
            }
        });

        lblCuotas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCuotas.setText("Cuotas");

        cmbCuotas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbCuotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[SELECCIONAR]", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        cmbCuotas.setEnabled(false);
        cmbCuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCuotasMouseClicked(evt);
            }
        });
        cmbCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCuotasActionPerformed(evt);
            }
        });

        dtcFecha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblFecha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblFecha.setText("Fecha");

        lblInteres.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblInteres.setText("Interes");

        lblIPorcentaje.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblIPorcentaje.setText("%");

        txtInteres.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInteresActionPerformed(evt);
            }
        });
        txtInteres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInteresKeyTyped(evt);
            }
        });

        lblSenia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblSenia.setText("Seña");

        txtSenia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtSenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeniaActionPerformed(evt);
            }
        });
        txtSenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeniaKeyTyped(evt);
            }
        });

        btnCalcularTotal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCalcularTotal.setText("Calcular Total");
        btnCalcularTotal.setMaximumSize(new java.awt.Dimension(116, 41));
        btnCalcularTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTotalActionPerformed(evt);
            }
        });

        lblDescuento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblDescuento.setText("Descuento");

        txtDescuento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyTyped(evt);
            }
        });

        lblMontoCuota.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblMontoCuota.setText("Monto por Cuota:");

        lblMoneyCuota.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblMoneyCuota.setText("$");

        txtMontoCuota.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtMontoCuota.setEnabled(false);
        txtMontoCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoCuotaActionPerformed(evt);
            }
        });

        txtMontoTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtMontoTotal.setEnabled(false);
        txtMontoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoTotalActionPerformed(evt);
            }
        });

        lblMoneyTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblMoneyTotal.setText("$");

        lblMontoTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblMontoTotal.setText("Monto Total:");

        btnGuardarPedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnGuardarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_save_16px.png"))); // NOI18N
        btnGuardarPedido.setText("Registrar Pedido");
        btnGuardarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPedidoActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        tblPedidos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        scpPedidos.setViewportView(tblPedidos);

        lblColor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblColor.setText("Color");

        txtColor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtColor.setEnabled(false);
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPedidoLayout = new javax.swing.GroupLayout(pnlPedido);
        pnlPedido.setLayout(pnlPedidoLayout);
        pnlPedidoLayout.setHorizontalGroup(
            pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scpPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPedidoLayout.createSequentialGroup()
                        .addComponent(lblMontoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMoneyTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuardarPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlPedidoLayout.createSequentialGroup()
                                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInteres)
                                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                                        .addComponent(lblIPorcentaje)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtInteres))
                                    .addComponent(lblEstadoPago))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPedidoLayout.createSequentialGroup()
                                .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSenia)
                            .addGroup(pnlPedidoLayout.createSequentialGroup()
                                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFecha)
                                    .addComponent(lblSenia))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPedidoLayout.createSequentialGroup()
                                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMetodoPago)
                                    .addComponent(cmbMetodoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCuotas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDescuento)
                            .addComponent(cmbCuotas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDescuento)
                            .addComponent(btnCalcularTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPedidoLayout.createSequentialGroup()
                        .addComponent(lblMontoCuota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMoneyCuota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                        .addComponent(lblDetalles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPedidoLayout.createSequentialGroup()
                        .addComponent(lblImporteM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCostoUnidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCostoUnidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarM, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifM, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarM, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPedidoLayout.createSequentialGroup()
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPedidoLayout.createSequentialGroup()
                                .addComponent(lblColor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtColor))
                            .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMaquinas)
                                .addComponent(txtMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnCantidad)
                            .addGroup(pnlPedidoLayout.createSequentialGroup()
                                .addComponent(lblCantidad)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlPedidoLayout.setVerticalGroup(
            pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaquinas)
                    .addComponent(lblCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDetalles)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModifM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCostoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblImporteM)
                        .addComponent(lblCostoUnidad))
                    .addComponent(btnAgregarM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                        .addComponent(lblMetodoPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbMetodoPago)
                            .addComponent(btnAgregarMetodo)))
                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                        .addComponent(lblEstadoPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPedidoLayout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInteres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIPorcentaje)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPedidoLayout.createSequentialGroup()
                        .addComponent(lblCuotas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescuento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                        .addComponent(lblSenia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCalcularTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoneyCuota)
                    .addComponent(lblMontoCuota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoneyTotal)
                    .addComponent(lblMontoTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMaquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlMaquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbApellidoMouseClicked
        txtBuscarC.setEnabled(true);
        txtBuscarC.setText("");
    }//GEN-LAST:event_rdbApellidoMouseClicked

    private void rdbApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbApellidoActionPerformed

    }//GEN-LAST:event_rdbApellidoActionPerformed

    private void rdbDniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbDniMouseClicked
        txtBuscarC.setEnabled(true);
        txtBuscarC.setText("");
    }//GEN-LAST:event_rdbDniMouseClicked

    private void rdbDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDniActionPerformed

    }//GEN-LAST:event_rdbDniActionPerformed

    private void txtBuscarCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCKeyTyped
        if (rdbDni.isSelected()) {

            char validar = evt.getKeyChar();

            if (Character.isLetter(validar)) {
                getToolkit().beep();
                evt.consume();

                JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar Números", "Advertencia", HEIGHT);
            }
        } else if (rdbApellido.isSelected()) {
            char validar = evt.getKeyChar();

            if (Character.isDigit(validar)) {
                getToolkit().beep();
                evt.consume();

                JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar Letras", "Advertencia", HEIGHT);
            }
        }
    }//GEN-LAST:event_txtBuscarCKeyTyped

    private void btnBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCActionPerformed
        if (rdbgCliente.getSelection() == null) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione algún método de búsqueda", "Advertencia", HEIGHT);
            rdbApellido.requestFocus();
        } else {

            if (rdbApellido.isSelected()) {
                if (txtBuscarC.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "No hay parámetro de búsqueda", "Advertencia", HEIGHT);
                    txtBuscarC.requestFocus();
                } else {
                    //                    UtilVista.cargarTablaCliente(cp.getCr().buscarClientePorApellido(txtBuscarC.getText()), tblCliente);
                }
            } else if (rdbDni.isSelected()) {
                if (txtBuscarC.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "No hay parámetro de búsqueda", "Advertencia", HEIGHT);
                    txtBuscarC.requestFocus();
                } else {
                    //                 UtilVista.cargarTablaCliente(cp.getCr().buscarClientePorDni(txtBuscarC.getText()), tblCliente);
                }
            }
        }
    }//GEN-LAST:event_btnBuscarCActionPerformed

    private void btnTodosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosClienteActionPerformed
        //      UtilVista.cargarTablaCliente(cp.getCr().traerClientes(), tblCliente);
        txtBuscarC.setText("");
        //estadoInicial();
    }//GEN-LAST:event_btnTodosClienteActionPerformed

    private void rdbNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbNombreMouseClicked

    private void rdbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbNombreActionPerformed

    private void rdbCODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbCODMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCODMouseClicked

    private void rdbCODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCODActionPerformed

    private void txtBuscarMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarMKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarMKeyTyped

    private void btnBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMActionPerformed

    private void btnTodasMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodasMaquinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTodasMaquinasActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaquinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaquinasActionPerformed

    private void txtCostoUnidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoUnidadKeyTyped

        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar Números", "Advertencia", HEIGHT);
        }
    }//GEN-LAST:event_txtCostoUnidadKeyTyped

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void btnAgregarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMActionPerformed

    private void btnModifMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifMActionPerformed

    private void btnEliminarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMActionPerformed

    private void cmbMetodoPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbMetodoPagoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMetodoPagoMouseClicked

    private void cmbMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodoPagoActionPerformed
        if (cmbMetodoPago.getSelectedIndex() == 0) {
            cmbEstado.setSelectedIndex(0);
            cmbEstado.setEnabled(false);
            cmbCuotas.setSelectedIndex(0);
            cmbCuotas.setEnabled(false);
        } else {

            /*
            MetodoDePago metodo = cp.getCpago().traerMetodoPorNombre(String.valueOf(cmbMetodoPago.getSelectedItem()));
            if (metodo.getCuotas() == true) {
                cmbCuotas.setEnabled(true);
                cmbEstado.setEnabled(false);
            } else {
                cmbCuotas.setEnabled(false);
                cmbEstado.setEnabled(true);
            }
            */
        }
    }//GEN-LAST:event_cmbMetodoPagoActionPerformed

    private void cmbEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbEstadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoMouseClicked

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnAgregarMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMetodoActionPerformed
        jdialogMetodoPago metodop = new jdialogMetodoPago(vp, true, cp, this, true);
        metodop.show();
    }//GEN-LAST:event_btnAgregarMetodoActionPerformed

    private void cmbCuotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCuotasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuotasMouseClicked

    private void cmbCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuotasActionPerformed

    private void txtInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInteresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInteresActionPerformed

    private void txtInteresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInteresKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar Números", "Advertencia", HEIGHT);
        }
    }//GEN-LAST:event_txtInteresKeyTyped

    private void txtSeniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeniaActionPerformed

    private void txtSeniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeniaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeniaKeyTyped

    private void btnCalcularTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTotalActionPerformed
        /*
        DecimalFormat df = new DecimalFormat(".00");

        int interes = 0;
        double descuento = 0;
        double total = Double.parseDouble(txtTotal.getText());
        double montoTotal = Double.parseDouble(txtTotal.getText());
        if (rootPaneCheckingEnabled) {

        }
        if (!txtInteres.getText().equals("") && !txtDescuento.getText().equals("")) {
            interes = Integer.parseInt(txtInteres.getText());
            descuento = Double.valueOf(txtDescuento.getText());
            montoTotal = (total + (total * interes) / 100) - descuento;
            txtMontoTotal.setText(String.valueOf(montoTotal));
        } else if (!txtInteres.getText().equals("")) {
            interes = Integer.parseInt(txtInteres.getText());
            montoTotal = total + ((total * interes) / 100);
            txtMontoTotal.setText(String.valueOf(montoTotal));
        } else if (!txtDescuento.getText().equals("")) {
            descuento = Double.valueOf(txtDescuento.getText());
            montoTotal = total - descuento;
            txtMontoTotal.setText(String.valueOf(montoTotal));
        } else {
            txtMontoTotal.setText(txtTotal.getText());
        }

        if (cmbCuotas.getSelectedIndex() != 0) {
            double montoXCuota = montoTotal / Integer.parseInt(String.valueOf(cmbCuotas.getSelectedItem()));
            cuotas = montoXCuota;
            txtCuotaPorMes.setText(String.valueOf(df.format(montoXCuota)));
        }

        btnGuardarPago.setEnabled(true);
        //        if (cmbCuotas.getSelectedIndex() != 0) {
            //            double montoXCuota = montoTotal / Integer.parseInt(String.valueOf(cmbCuotas.getSelectedItem()));
            //            txtCuotaPorMes.setText(String.valueOf(montoXCuota));
            //        }
        */
    }//GEN-LAST:event_btnCalcularTotalActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void txtDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo puede ingresar Números", "Advertencia", HEIGHT);
        }
    }//GEN-LAST:event_txtDescuentoKeyTyped

    private void txtMontoCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoCuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoCuotaActionPerformed

    private void txtMontoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoTotalActionPerformed

    private void btnGuardarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPedidoActionPerformed
        /*
        Date fecha = dtcFecha.getDate();

        if (txtCliente.getText().equals("")
            || txtIDCliente.getText().equals("")
            || txtVehiculo.getText().equals("")
            || txtIDProforma.getText().equals("")
            || fecha == null
            || cmbPagadoPor.getSelectedIndex() == 0
            || cmbMetodoPago.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(rootPane, "Hay campos incompletos");
        } else {

            try {

                Cliente cliente = cp.getCr().traerCliente(Integer.parseInt(txtIDCliente.getText()));
                Proforma proforma = cp.getCpro().buscarProforma(Integer.parseInt(txtIDProforma.getText()));
                MetodoDePago metodoP = cp.getCpago().traerMetodoPorNombre(String.valueOf(cmbMetodoPago.getSelectedItem()));
                Seguro seguro = cp.getCr().buscarSeguro(String.valueOf(cmbPagadoPor.getSelectedItem()));
                int interes = 0;
                double descuento = 0;
                double montoTotal = Double.parseDouble(txtMontoTotal.getText());

                if (!txtInteres.getText().equals("") && !txtDescuento.getText().equals("")) {
                    interes = Integer.parseInt(txtInteres.getText());
                    descuento = Double.parseDouble(txtDescuento.getText());
                } else if (!txtInteres.getText().equals("")) {
                    interes = Integer.parseInt(txtInteres.getText());
                } else if (!txtDescuento.getText().equals("")) {
                    descuento = Double.parseDouble(txtDescuento.getText());
                }

                if (metodoP.getCuotas() == true) {
                    Pago pago = cp.getCpago().nuevoPago(montoTotal, fecha, "Pendiente", interes, descuento, cliente, seguro, metodoP, proforma);
                    int cantCuotas = Integer.parseInt((String) cmbCuotas.getSelectedItem());
                    for (int i = 1; i <= cantCuotas; i++) {
                        cp.getCpago().nuevaCuota(cuotas, "Pendiente", pago);
                    }
                    JOptionPane.showMessageDialog(rootPane, "El Pago se registró exitosamente");
                    estadoInicial();
                    cuotas = 0;
                } else {
                    if (cmbEstado.getSelectedIndex() != 0) {
                        cp.getCpago().nuevoPago(montoTotal, fecha, String.valueOf(cmbEstado.getSelectedItem()), interes, descuento, cliente, seguro, metodoP, proforma);
                        JOptionPane.showMessageDialog(rootPane, "El Pago se registró exitosamente");
                        estadoInicial();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Hay campos incompletos");
                    }
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }*/
    }//GEN-LAST:event_btnGuardarPedidoActionPerformed

    private void rdbCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbCelularMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCelularMouseClicked

    private void rdbCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCelularActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarM;
    private javax.swing.JButton btnAgregarMetodo;
    private javax.swing.JButton btnBuscarC;
    private javax.swing.JButton btnBuscarM;
    private javax.swing.JButton btnCalcularTotal;
    private javax.swing.JButton btnEliminarM;
    private javax.swing.JButton btnGuardarPedido;
    private javax.swing.JButton btnModifM;
    private javax.swing.JButton btnTodasMaquinas;
    private javax.swing.JButton btnTodosCliente;
    private javax.swing.JComboBox<String> cmbCuotas;
    private javax.swing.JComboBox<String> cmbEstado;
    public javax.swing.JComboBox<String> cmbMetodoPago;
    private com.toedter.calendar.JDateChooser dtcFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCostoUnidad;
    private javax.swing.JLabel lblCuotas;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEstadoPago;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIPorcentaje;
    private javax.swing.JLabel lblImporteM;
    private javax.swing.JLabel lblInteres;
    private javax.swing.JLabel lblMaquinas;
    private javax.swing.JLabel lblMetodoPago;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblMoneyCuota;
    private javax.swing.JLabel lblMoneyTotal;
    private javax.swing.JLabel lblMontoCuota;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblSenia;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlMaquinas;
    private javax.swing.JPanel pnlPedido;
    private javax.swing.JRadioButton rdbApellido;
    private javax.swing.JRadioButton rdbCOD;
    private javax.swing.JRadioButton rdbCelular;
    private javax.swing.JRadioButton rdbDni;
    private javax.swing.JRadioButton rdbNombre;
    private javax.swing.ButtonGroup rdbgCliente;
    private javax.swing.ButtonGroup rdbgMaquina;
    private javax.swing.JScrollPane scpClientes;
    private javax.swing.JScrollPane scpMaquinas;
    private javax.swing.JScrollPane scpPedidos;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblMaquinas;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtBuscarC;
    private javax.swing.JTextField txtBuscarM;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtCostoUnidad;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtMaquinas;
    private javax.swing.JTextField txtMontoCuota;
    private javax.swing.JTextField txtMontoTotal;
    private javax.swing.JTextField txtSenia;
    private javax.swing.JTextField txtSubTotal;
    // End of variables declaration//GEN-END:variables
}
