/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorPrincipal;
import static java.awt.Frame.MAXIMIZED_BOTH;
import vista.Caja.ifrmMovimientos;
import vista.Clientes.ifrmAgenda;
import vista.Maquinas.ifrmMaquinas;
import vista.Pedido.ifrmPedido;
import vista.Stock.ifrmStock;
import vista.Stock.jdialogUnidadMedida;

/**
 *
 * @author juanm
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    ControladorPrincipal cp;

    public frmPrincipal(ControladorPrincipal contp) {
        cp = contp;
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        pnlPedidos = new javax.swing.JPanel();
        icoPedidos = new javax.swing.JLabel();
        lblPedidos = new javax.swing.JLabel();
        pnlClientes = new javax.swing.JPanel();
        icoClientes = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        pnlMaquinas = new javax.swing.JPanel();
        icoMaquinas = new javax.swing.JLabel();
        lblMaquinas = new javax.swing.JLabel();
        pnlStock = new javax.swing.JPanel();
        icoStock = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        pnlMovimientos = new javax.swing.JPanel();
        icoMovimientos = new javax.swing.JLabel();
        lblMovimientos = new javax.swing.JLabel();
        tbpNoticias = new javax.swing.JTabbedPane();
        pnlNoticias = new javax.swing.JPanel();
        scpNoticias = new javax.swing.JScrollPane();
        lstNoticias = new javax.swing.JList<>();
        pnlCajaChica = new javax.swing.JPanel();
        pnlCajChica = new javax.swing.JPanel();
        lblMoneda = new javax.swing.JLabel();
        lblCajaChica = new javax.swing.JLabel();
        btnDepositar = new javax.swing.JButton();
        btnExtraer = new javax.swing.JButton();
        dktEscritorio = new javax.swing.JDesktopPane();
        mnuBarPrincipal = new javax.swing.JMenuBar();
        mnuPedidos = new javax.swing.JMenu();
        imnuNuevoPedido = new javax.swing.JMenuItem();
        imnuListaPedidos = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        imnuRegistrarCliente = new javax.swing.JMenuItem();
        imnuAgenda = new javax.swing.JMenuItem();
        mnuMaquinas = new javax.swing.JMenu();
        imnuListadoMaquinas = new javax.swing.JMenuItem();
        imnuGaleria = new javax.swing.JMenuItem();
        mnuStock = new javax.swing.JMenu();
        imnuVerStock = new javax.swing.JMenuItem();
        imnuRegistrarCompra = new javax.swing.JMenuItem();
        inmuMarcaProductos = new javax.swing.JMenuItem();
        imnuUnidadMedida = new javax.swing.JMenuItem();
        mnuCaja = new javax.swing.JMenu();
        imnuMovimientos = new javax.swing.JMenuItem();
        imnuRegistrarPago = new javax.swing.JMenuItem();
        imnuListaPagos = new javax.swing.JMenuItem();
        imnuListaCompras = new javax.swing.JMenuItem();
        imnuMetodoPago = new javax.swing.JMenuItem();
        mnuServicios = new javax.swing.JMenu();
        imnuRegistrarServicio = new javax.swing.JMenuItem();
        imnuPagarServicio = new javax.swing.JMenuItem();
        mnuEstructurales = new javax.swing.JMenu();
        imnuDatos = new javax.swing.JMenuItem();
        imnuClaveSeguridad = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMenu.setBackground(java.awt.Color.white);

        pnlPedidos.setBackground(java.awt.Color.lightGray);
        pnlPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPedidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPedidosMouseExited(evt);
            }
        });

        icoPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblPedidos.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblPedidos.setText("Nuevo Pedido");

        javax.swing.GroupLayout pnlPedidosLayout = new javax.swing.GroupLayout(pnlPedidos);
        pnlPedidos.setLayout(pnlPedidosLayout);
        pnlPedidosLayout.setHorizontalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosLayout.createSequentialGroup()
                .addComponent(icoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPedidosLayout.setVerticalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlClientes.setBackground(java.awt.Color.lightGray);
        pnlClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlClientesMouseExited(evt);
            }
        });

        icoClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblClientes.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblClientes.setText("Clientes");

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addComponent(icoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlMaquinas.setBackground(java.awt.Color.lightGray);
        pnlMaquinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMaquinasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMaquinasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMaquinasMouseExited(evt);
            }
        });

        icoMaquinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMaquinas.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblMaquinas.setText("Máquinas");

        javax.swing.GroupLayout pnlMaquinasLayout = new javax.swing.GroupLayout(pnlMaquinas);
        pnlMaquinas.setLayout(pnlMaquinasLayout);
        pnlMaquinasLayout.setHorizontalGroup(
            pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaquinasLayout.createSequentialGroup()
                .addComponent(icoMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblMaquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMaquinasLayout.setVerticalGroup(
            pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoMaquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblMaquinas, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlStock.setBackground(java.awt.Color.lightGray);
        pnlStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlStockMouseExited(evt);
            }
        });

        icoStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblStock.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblStock.setText("Stock");

        javax.swing.GroupLayout pnlStockLayout = new javax.swing.GroupLayout(pnlStock);
        pnlStock.setLayout(pnlStockLayout);
        pnlStockLayout.setHorizontalGroup(
            pnlStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockLayout.createSequentialGroup()
                .addComponent(icoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStockLayout.setVerticalGroup(
            pnlStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblStock, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlMovimientos.setBackground(java.awt.Color.lightGray);
        pnlMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMovimientosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMovimientosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMovimientosMouseExited(evt);
            }
        });

        icoMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMovimientos.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblMovimientos.setText("Movimientos de Caja");

        javax.swing.GroupLayout pnlMovimientosLayout = new javax.swing.GroupLayout(pnlMovimientos);
        pnlMovimientos.setLayout(pnlMovimientosLayout);
        pnlMovimientosLayout.setHorizontalGroup(
            pnlMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMovimientosLayout.createSequentialGroup()
                .addComponent(icoMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMovimientosLayout.setVerticalGroup(
            pnlMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tbpNoticias.setBackground(new java.awt.Color(255, 255, 255));
        tbpNoticias.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        scpNoticias.setBorder(null);

        lstNoticias.setBackground(java.awt.Color.darkGray);
        lstNoticias.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lstNoticias.setForeground(new java.awt.Color(255, 255, 0));
        lstNoticias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstNoticias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstNoticias.setSelectionBackground(new java.awt.Color(102, 102, 102));
        lstNoticias.setSelectionForeground(new java.awt.Color(255, 255, 51));
        scpNoticias.setViewportView(lstNoticias);

        javax.swing.GroupLayout pnlNoticiasLayout = new javax.swing.GroupLayout(pnlNoticias);
        pnlNoticias.setLayout(pnlNoticiasLayout);
        pnlNoticiasLayout.setHorizontalGroup(
            pnlNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpNoticias, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlNoticiasLayout.setVerticalGroup(
            pnlNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpNoticias, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        tbpNoticias.addTab("Noticias", pnlNoticias);

        lblMoneda.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblMoneda.setText("$");

        lblCajaChica.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        btnDepositar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnExtraer.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnExtraer.setText("Extraer");
        btnExtraer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCajChicaLayout = new javax.swing.GroupLayout(pnlCajChica);
        pnlCajChica.setLayout(pnlCajChicaLayout);
        pnlCajChicaLayout.setHorizontalGroup(
            pnlCajChicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCajChicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCajChicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajChicaLayout.createSequentialGroup()
                        .addComponent(lblMoneda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCajaChica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCajChicaLayout.createSequentialGroup()
                        .addGroup(pnlCajChicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExtraer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDepositar, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnlCajChicaLayout.setVerticalGroup(
            pnlCajChicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCajChicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCajChicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCajaChica, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExtraer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout pnlCajaChicaLayout = new javax.swing.GroupLayout(pnlCajaChica);
        pnlCajaChica.setLayout(pnlCajaChicaLayout);
        pnlCajaChicaLayout.setHorizontalGroup(
            pnlCajaChicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCajChica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCajaChicaLayout.setVerticalGroup(
            pnlCajaChicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCajChica, javax.swing.GroupLayout.PREFERRED_SIZE, 167, Short.MAX_VALUE)
        );

        tbpNoticias.addTab("Caja Chica", pnlCajaChica);

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpNoticias)
            .addComponent(pnlMovimientos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMaquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbpNoticias, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout dktEscritorioLayout = new javax.swing.GroupLayout(dktEscritorio);
        dktEscritorio.setLayout(dktEscritorioLayout);
        dktEscritorioLayout.setHorizontalGroup(
            dktEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        dktEscritorioLayout.setVerticalGroup(
            dktEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );

        mnuBarPrincipal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        mnuPedidos.setText("Pedidos");
        mnuPedidos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPedidosActionPerformed(evt);
            }
        });

        imnuNuevoPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        imnuNuevoPedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuNuevoPedido.setText("Nuevo Pedido");
        imnuNuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuNuevoPedidoActionPerformed(evt);
            }
        });
        mnuPedidos.add(imnuNuevoPedido);

        imnuListaPedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        imnuListaPedidos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuListaPedidos.setText("Lista de Pedidos");
        imnuListaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuListaPedidosActionPerformed(evt);
            }
        });
        mnuPedidos.add(imnuListaPedidos);

        mnuBarPrincipal.add(mnuPedidos);

        mnuClientes.setText("Clientes");
        mnuClientes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        imnuRegistrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        imnuRegistrarCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuRegistrarCliente.setText("Registrar Cliente");
        imnuRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuRegistrarClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(imnuRegistrarCliente);

        imnuAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        imnuAgenda.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuAgenda.setText("Agenda");
        imnuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuAgendaActionPerformed(evt);
            }
        });
        mnuClientes.add(imnuAgenda);

        mnuBarPrincipal.add(mnuClientes);

        mnuMaquinas.setText("Máquinas");
        mnuMaquinas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        imnuListadoMaquinas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        imnuListadoMaquinas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuListadoMaquinas.setText("Listado de Máquinas");
        imnuListadoMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuListadoMaquinasActionPerformed(evt);
            }
        });
        mnuMaquinas.add(imnuListadoMaquinas);

        imnuGaleria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        imnuGaleria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuGaleria.setText("Galería");
        imnuGaleria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuGaleriaActionPerformed(evt);
            }
        });
        mnuMaquinas.add(imnuGaleria);

        mnuBarPrincipal.add(mnuMaquinas);

        mnuStock.setText("Stock");
        mnuStock.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        imnuVerStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        imnuVerStock.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuVerStock.setText("Ver Stock");
        imnuVerStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuVerStockActionPerformed(evt);
            }
        });
        mnuStock.add(imnuVerStock);

        imnuRegistrarCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        imnuRegistrarCompra.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuRegistrarCompra.setText("Registrar Compra de Producto");
        imnuRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuRegistrarCompraActionPerformed(evt);
            }
        });
        mnuStock.add(imnuRegistrarCompra);

        inmuMarcaProductos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        inmuMarcaProductos.setText("Marcas de Productos");
        inmuMarcaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inmuMarcaProductosActionPerformed(evt);
            }
        });
        mnuStock.add(inmuMarcaProductos);

        imnuUnidadMedida.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuUnidadMedida.setText("Unidades de Medida");
        imnuUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuUnidadMedidaActionPerformed(evt);
            }
        });
        mnuStock.add(imnuUnidadMedida);

        mnuBarPrincipal.add(mnuStock);

        mnuCaja.setText("Caja");
        mnuCaja.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        imnuMovimientos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        imnuMovimientos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuMovimientos.setText("Movimientos");
        imnuMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuMovimientosActionPerformed(evt);
            }
        });
        mnuCaja.add(imnuMovimientos);

        imnuRegistrarPago.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuRegistrarPago.setText("Registrar Pago");
        imnuRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuRegistrarPagoActionPerformed(evt);
            }
        });
        mnuCaja.add(imnuRegistrarPago);

        imnuListaPagos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuListaPagos.setText("Lista de Pagos");
        imnuListaPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuListaPagosActionPerformed(evt);
            }
        });
        mnuCaja.add(imnuListaPagos);

        imnuListaCompras.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuListaCompras.setText("Lista de Compras");
        imnuListaCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuListaComprasActionPerformed(evt);
            }
        });
        mnuCaja.add(imnuListaCompras);

        imnuMetodoPago.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuMetodoPago.setText("Método de Pago");
        imnuMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuMetodoPagoActionPerformed(evt);
            }
        });
        mnuCaja.add(imnuMetodoPago);

        mnuBarPrincipal.add(mnuCaja);

        mnuServicios.setText("Servicios");
        mnuServicios.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        imnuRegistrarServicio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuRegistrarServicio.setText("Registrar Servicio");
        mnuServicios.add(imnuRegistrarServicio);

        imnuPagarServicio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuPagarServicio.setText("Pagar Servicio");
        mnuServicios.add(imnuPagarServicio);

        mnuBarPrincipal.add(mnuServicios);

        mnuEstructurales.setText("Estructurales");
        mnuEstructurales.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        imnuDatos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        imnuDatos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuDatos.setText("Ver Datos");
        imnuDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuDatosActionPerformed(evt);
            }
        });
        mnuEstructurales.add(imnuDatos);

        imnuClaveSeguridad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imnuClaveSeguridad.setText("Cambiar Clave de Seguridad");
        imnuClaveSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuClaveSeguridadActionPerformed(evt);
            }
        });
        mnuEstructurales.add(imnuClaveSeguridad);

        mnuBarPrincipal.add(mnuEstructurales);

        setJMenuBar(mnuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dktEscritorio)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dktEscritorio)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imnuNuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuNuevoPedidoActionPerformed
        // ifrmListaProformas lp = new ifrmListaProformas(cp, this);
        // ifrmProforma proforma = new ifrmProforma(cp, lp, true);
        // cp.abrirVentana(proforma, dktEscritorio);
    }//GEN-LAST:event_imnuNuevoPedidoActionPerformed

    private void imnuListaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuListaPedidosActionPerformed
        // ifrmListaProformas listaV = new ifrmListaProformas(cp, this);
        // cp.abrirVentana(listaV, dktEscritorio);
    }//GEN-LAST:event_imnuListaPedidosActionPerformed

    private void mnuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPedidosActionPerformed

    }//GEN-LAST:event_mnuPedidosActionPerformed

    private void imnuRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuRegistrarClienteActionPerformed
        // ifrmRegistro registro = new ifrmRegistro(cp, this);
        // cp.abrirVentana(registro, dktEscritorio);
    }//GEN-LAST:event_imnuRegistrarClienteActionPerformed

    private void imnuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuAgendaActionPerformed
        ifrmAgenda agenda = new ifrmAgenda(cp);
        cp.abrirVentana(agenda, dktEscritorio);
    }//GEN-LAST:event_imnuAgendaActionPerformed

    private void imnuVerStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuVerStockActionPerformed
        // ifrmStock123 stock = new ifrmStock123(cp, this, false);
        // cp.abrirVentana(stock, dktEscritorio);
    }//GEN-LAST:event_imnuVerStockActionPerformed

    private void imnuRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuRegistrarCompraActionPerformed
        // ifrmCompra compra = new ifrmCompra(cp, this);
        // cp.abrirVentana(compra, dktEscritorio);
    }//GEN-LAST:event_imnuRegistrarCompraActionPerformed

    private void inmuMarcaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inmuMarcaProductosActionPerformed
        //ifrmStock stock = new ifrmStock123(cp, this, false);
        //jdialogMarcaProduc marca = new jdialogMarcaProduc(this, true, cp, stock, false);
        //marca.show();
    }//GEN-LAST:event_inmuMarcaProductosActionPerformed

    private void imnuUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuUnidadMedidaActionPerformed
        ifrmMaquinas maq = new ifrmMaquinas(cp);
        jdialogUnidadMedida um = new jdialogUnidadMedida(this, true, cp, maq, false);
        um.show();
    }//GEN-LAST:event_imnuUnidadMedidaActionPerformed

    private void imnuMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuMovimientosActionPerformed
        // ifrmCaja caja = new ifrmCaja(cp, this);
        // cp.abrirVentana(caja, dktEscritorio);
    }//GEN-LAST:event_imnuMovimientosActionPerformed

    private void imnuRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuRegistrarPagoActionPerformed
    }//GEN-LAST:event_imnuRegistrarPagoActionPerformed

    private void imnuListaPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuListaPagosActionPerformed
        //    ifrmListaDePagos listaPagos = new ifrmListaDePagos(cp, this);
        //   cp.abrirVentana(listaPagos, dktEscritorio);
    }//GEN-LAST:event_imnuListaPagosActionPerformed

    private void imnuListaComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuListaComprasActionPerformed
        // ifrmListaCompras listac = new ifrmListaCompras(cp, this);
        // cp.abrirVentana(listac, dktEscritorio);
    }//GEN-LAST:event_imnuListaComprasActionPerformed

    private void imnuMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuMetodoPagoActionPerformed
        //ifrmPago pago = new ifrmPedido2(cp, this);
        //jdialogMetodoPago metodop = new jdialogMetodoPago(this, true, cp, pago, false);
        //metodop.show();
    }//GEN-LAST:event_imnuMetodoPagoActionPerformed

    private void imnuListadoMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuListadoMaquinasActionPerformed
        // ifrmEmpleados empleados = new ifrmEmpleados(cp, this);
        // cp.abrirVentana(empleados, dktEscritorio);
    }//GEN-LAST:event_imnuListadoMaquinasActionPerformed

    private void imnuDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuDatosActionPerformed
        /*        ifrmTaller taller = new ifrmTaller(cp, this);

        dktEscritorio.removeAll();
        dktEscritorio.updateUI();
        dktEscritorio.add(taller);
        Dimension tamanioEscritorio = dktEscritorio.getSize();
        Dimension tamanioVentana = taller.getSize();
        taller.setLocation((tamanioEscritorio.width - tamanioVentana.width) / 2, (tamanioEscritorio.height - tamanioVentana.height) / 2);
        taller.show();
         */
    }//GEN-LAST:event_imnuDatosActionPerformed

    private void imnuClaveSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuClaveSeguridadActionPerformed
        // jdialogCambiarClave clave = new jdialogCambiarClave(this, true, cp);
        // clave.show();
    }//GEN-LAST:event_imnuClaveSeguridadActionPerformed

    private void pnlPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPedidosMouseClicked
        ifrmPedido pedido = new ifrmPedido(cp, this);
        cp.abrirVentana(pedido, dktEscritorio);
    }//GEN-LAST:event_pnlPedidosMouseClicked

    private void pnlPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPedidosMouseEntered

    }//GEN-LAST:event_pnlPedidosMouseEntered

    private void pnlPedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPedidosMouseExited

    }//GEN-LAST:event_pnlPedidosMouseExited

    private void pnlClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClientesMouseClicked
        ifrmAgenda agenda = new ifrmAgenda(cp);
        cp.abrirVentana(agenda, dktEscritorio);
    }//GEN-LAST:event_pnlClientesMouseClicked

    private void pnlClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClientesMouseEntered

    }//GEN-LAST:event_pnlClientesMouseEntered

    private void pnlClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClientesMouseExited

    }//GEN-LAST:event_pnlClientesMouseExited

    private void pnlMaquinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMaquinasMouseClicked
        ifrmMaquinas maq = new ifrmMaquinas(cp);
        cp.abrirVentana(maq, dktEscritorio);
    }//GEN-LAST:event_pnlMaquinasMouseClicked

    private void pnlMaquinasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMaquinasMouseEntered

    }//GEN-LAST:event_pnlMaquinasMouseEntered

    private void pnlMaquinasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMaquinasMouseExited

    }//GEN-LAST:event_pnlMaquinasMouseExited

    private void pnlStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStockMouseClicked
        ifrmStock stock = new ifrmStock(cp, this, false);
        cp.abrirVentana(stock, dktEscritorio);
    }//GEN-LAST:event_pnlStockMouseClicked

    private void pnlStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStockMouseEntered

    }//GEN-LAST:event_pnlStockMouseEntered

    private void pnlStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStockMouseExited

    }//GEN-LAST:event_pnlStockMouseExited

    private void pnlMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMovimientosMouseClicked
        ifrmMovimientos caja = new ifrmMovimientos(cp, this);
        cp.abrirVentana(caja, dktEscritorio);
    }//GEN-LAST:event_pnlMovimientosMouseClicked

    private void pnlMovimientosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMovimientosMouseEntered

    }//GEN-LAST:event_pnlMovimientosMouseEntered

    private void pnlMovimientosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMovimientosMouseExited

    }//GEN-LAST:event_pnlMovimientosMouseExited

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        /*ifrmCajaChica caja = new ifrmCajaChica(cp, "Depositar", this);

        jdialogCajaChica caja = new jdialogCajaChica(this, true, cp, "Depositar");
        caja.show();
        CajaChica cajaActual = cp.getcCaja().traerCaja();
        lblCajaChica.setText(String.valueOf(cajaActual.getSaldoActual()));
         */
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnExtraerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraerActionPerformed
        /*ifrmCajaChica caja = new ifrmCajaChica(cp, "Extraer", this);

        this.dktEscritorio.add(caja);
        Dimension tamanioEscritorio = this.dktEscritorio.getSize();
        Dimension tamanioVentana = caja.getSize();
        caja.setLocation((tamanioEscritorio.width - tamanioVentana.width) / 2, (tamanioEscritorio.height - tamanioVentana.height) / 2);
        caja.show();

        jdialogCajaChica caja = new jdialogCajaChica(this, true, cp, "Extraer");
        caja.show();
        CajaChica cajaActual = cp.getcCaja().traerCaja();

        lblCajaChica.setText(String.valueOf(cajaActual.getSaldoActual()));

         */
    }//GEN-LAST:event_btnExtraerActionPerformed

    private void imnuGaleriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuGaleriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imnuGaleriaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnExtraer;
    public javax.swing.JDesktopPane dktEscritorio;
    private javax.swing.JLabel icoClientes;
    private javax.swing.JLabel icoMaquinas;
    private javax.swing.JLabel icoMovimientos;
    private javax.swing.JLabel icoPedidos;
    private javax.swing.JLabel icoStock;
    private javax.swing.JMenuItem imnuAgenda;
    private javax.swing.JMenuItem imnuClaveSeguridad;
    private javax.swing.JMenuItem imnuDatos;
    private javax.swing.JMenuItem imnuGaleria;
    private javax.swing.JMenuItem imnuListaCompras;
    private javax.swing.JMenuItem imnuListaPagos;
    private javax.swing.JMenuItem imnuListaPedidos;
    private javax.swing.JMenuItem imnuListadoMaquinas;
    private javax.swing.JMenuItem imnuMetodoPago;
    private javax.swing.JMenuItem imnuMovimientos;
    private javax.swing.JMenuItem imnuNuevoPedido;
    private javax.swing.JMenuItem imnuPagarServicio;
    private javax.swing.JMenuItem imnuRegistrarCliente;
    private javax.swing.JMenuItem imnuRegistrarCompra;
    private javax.swing.JMenuItem imnuRegistrarPago;
    private javax.swing.JMenuItem imnuRegistrarServicio;
    private javax.swing.JMenuItem imnuUnidadMedida;
    private javax.swing.JMenuItem imnuVerStock;
    private javax.swing.JMenuItem inmuMarcaProductos;
    public javax.swing.JLabel lblCajaChica;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblMaquinas;
    private javax.swing.JLabel lblMoneda;
    private javax.swing.JLabel lblMovimientos;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JLabel lblStock;
    public javax.swing.JList<String> lstNoticias;
    private javax.swing.JMenuBar mnuBarPrincipal;
    private javax.swing.JMenu mnuCaja;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuEstructurales;
    private javax.swing.JMenu mnuMaquinas;
    private javax.swing.JMenu mnuPedidos;
    private javax.swing.JMenu mnuServicios;
    private javax.swing.JMenu mnuStock;
    private javax.swing.JPanel pnlCajChica;
    private javax.swing.JPanel pnlCajaChica;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlMaquinas;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMovimientos;
    private javax.swing.JPanel pnlNoticias;
    private javax.swing.JPanel pnlPedidos;
    private javax.swing.JPanel pnlStock;
    private javax.swing.JScrollPane scpNoticias;
    private javax.swing.JTabbedPane tbpNoticias;
    // End of variables declaration//GEN-END:variables
}
