/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Maquinas;

import controlador.ControladorPrincipal;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Maquinas;
import modelo.Medidas;
import modelo.UnidadDeMedida;
import vista.Stock.jdialogUnidadMedida;
import vista.UtilVista;
import vista.frmPrincipal;

/**
 *
 * @author juanm
 */
public class ifrmMaquinas extends javax.swing.JInternalFrame {

    ControladorPrincipal cp;
    frmPrincipal vp;
    String action;

    String nombre, cod, descrip;

    /**
     * Creates new form ifrmMaquinas
     */
    public ifrmMaquinas(ControladorPrincipal cp) {
        initComponents();
        this.cp = cp;
        initState();
    }

    public void initState() {
        UtilVista.cargarTablaMaquinas(cp.getCs().findAllMaquinas(), tblMaquinas);
        UtilVista.cargarCombo(cp.getCs().findAllUnidadDeMedida(), cmbUnidadMedida);
        cleanAll();
        BlockTxt(false);
    }

    public void cancel() {
        action = "";
        cleanAll();
        BlockTxt(false);
        BlockButtons();
    }

    public void getValores() {
        nombre = txtNombre.getText();
        cod = txtCodigo.getText();
        descrip = txtaDescip.getText();
    }

    public void cleanAll() {
        txtNombre.setText("");;
        txtCodigo.setText("");
        txtMedida.setText("");
        txtCant.setText("");
        txtaDescip.setText("");

        cmbUnidadMedida.setSelectedIndex(0);
    }

    public void BlockButtons() {
        btnCancelar.setEnabled(false);
        btnNuevoMaquina.setEnabled(true);
        btnModif.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnUnidMed.setEnabled(false);
    }

    public void BlockTxt(boolean block) {
        txtNombre.setEnabled(block);
        txtCodigo.setEnabled(block);
        txtMedida.setEnabled(block);
        txtCant.setEnabled(block);
        scpDescrip.setEnabled(block);
        txtaDescip.setEnabled(block);

        cmbUnidadMedida.setEnabled(block);

        if (block == false) {
            txtNombre.setDisabledTextColor(Color.DARK_GRAY);
            txtCodigo.setDisabledTextColor(Color.DARK_GRAY);
            txtMedida.setDisabledTextColor(Color.DARK_GRAY);
            txtCant.setDisabledTextColor(Color.DARK_GRAY);
            txtaDescip.setDisabledTextColor(Color.DARK_GRAY);
        }
    }

    public void maquinaAction(String accion) {

        if (accion == "new") {
            UtilVista.cargarTablaMedidas(null, tblMedidas);
            action = accion;
            btnNuevoMaquina.setEnabled(false);
            btnCancelar.setEnabled(true);
            btnGuardar.setEnabled(true);
            btnUnidMed.setEnabled(true);
            btnModif.setEnabled(false);
            btnEliminar.setEnabled(false);
            BlockTxt(true);
        } else if (accion == "edit") {
            action = accion;
            btnCancelar.setEnabled(true);
            btnNuevoMaquina.setEnabled(false);
            btnModif.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnGuardar.setEnabled(true);
            BlockTxt(true);
            txtMedida.setEnabled(false);
            txtCant.setEnabled(false);
            cmbUnidadMedida.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMaquinas = new javax.swing.JPanel();
        rdbNombre = new javax.swing.JRadioButton();
        rdbCOD = new javax.swing.JRadioButton();
        lblEstado = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        cmbBaja = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        scpMaquinas = new javax.swing.JScrollPane();
        tblMaquinas = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnNuevoMaquina = new javax.swing.JButton();
        btnModif = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblDescrip = new javax.swing.JLabel();
        scpDescrip = new javax.swing.JScrollPane();
        txtaDescip = new javax.swing.JTextArea();
        pnlMedidas = new javax.swing.JPanel();
        lblMedida = new javax.swing.JLabel();
        txtMedida = new javax.swing.JTextField();
        lblCant = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        cmbUnidadMedida = new javax.swing.JComboBox<>();
        scpMedidas = new javax.swing.JScrollPane();
        tblMedidas = new javax.swing.JTable();
        btnAgregarM = new javax.swing.JButton();
        btnModifM = new javax.swing.JButton();
        btnUnidMed = new javax.swing.JButton();
        btnElimM = new javax.swing.JButton();
        pnlImagenes = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        pnlImagen = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        lblCantidad = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnVerGaleria = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Máquinas");
        setFrameIcon(null);

        pnlMaquinas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Máquinas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N

        rdbNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdbNombre.setText("Nombre");
        rdbNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbNombreMouseClicked(evt);
            }
        });
        rdbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNombreActionPerformed(evt);
            }
        });

        rdbCOD.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdbCOD.setText("COD");
        rdbCOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbCODMouseClicked(evt);
            }
        });
        rdbCOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCODActionPerformed(evt);
            }
        });

        lblEstado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblEstado.setText("Estado");

        txtBuscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        cmbBaja.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbBaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Eliminados" }));
        cmbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBajaActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_search_16px.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnTodos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnTodos.setText("Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        tblMaquinas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblMaquinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMaquinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaquinasMouseClicked(evt);
            }
        });
        scpMaquinas.setViewportView(tblMaquinas);
        if (tblMaquinas.getColumnModel().getColumnCount() > 0) {
            tblMaquinas.getColumnModel().getColumn(0).setResizable(false);
            tblMaquinas.getColumnModel().getColumn(1).setResizable(false);
        }

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_multiply_16px.png"))); // NOI18N
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevoMaquina.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnNuevoMaquina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_add_16px.png"))); // NOI18N
        btnNuevoMaquina.setText("Nueva");
        btnNuevoMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoMaquinaActionPerformed(evt);
            }
        });

        btnModif.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnModif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_edit_16px.png"))); // NOI18N
        btnModif.setText("Modificar");
        btnModif.setEnabled(false);
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_trash_16px.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_save_16px.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMaquinasLayout = new javax.swing.GroupLayout(pnlMaquinas);
        pnlMaquinas.setLayout(pnlMaquinasLayout);
        pnlMaquinasLayout.setHorizontalGroup(
            pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaquinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMaquinasLayout.createSequentialGroup()
                        .addComponent(rdbNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbCOD)
                        .addGap(38, 38, 38)
                        .addComponent(lblEstado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlMaquinasLayout.createSequentialGroup()
                        .addGroup(pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scpMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(pnlMaquinasLayout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTodos))
                            .addGroup(pnlMaquinasLayout.createSequentialGroup()
                                .addComponent(btnNuevoMaquina, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModif, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                            .addGroup(pnlMaquinasLayout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        pnlMaquinasLayout.setVerticalGroup(
            pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaquinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbNombre)
                    .addComponent(rdbCOD)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModif, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNuevoMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Máquinas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblNombre.setText("Nombre *");

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCodigo.setText("COD *");

        txtCodigo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        lblDescrip.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblDescrip.setText("Descripción");

        txtaDescip.setColumns(20);
        txtaDescip.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtaDescip.setRows(5);
        scpDescrip.setViewportView(txtaDescip);

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo)
                    .addComponent(txtNombre)
                    .addComponent(scpDescrip, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblCodigo)
                            .addComponent(lblDescrip))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescrip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpDescrip)
                .addContainerGap())
        );

        pnlMedidas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N

        lblMedida.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblMedida.setText("Medida");

        txtMedida.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblCant.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCant.setText("Cantidad");

        txtCant.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCant.setPreferredSize(new java.awt.Dimension(92, 22));
        txtCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantActionPerformed(evt);
            }
        });

        cmbUnidadMedida.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUnidadMedidaActionPerformed(evt);
            }
        });

        tblMedidas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblMedidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medida", "Cantidad", "U. Medida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedidasMouseClicked(evt);
            }
        });
        scpMedidas.setViewportView(tblMedidas);

        btnAgregarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_plus_math_16px.png"))); // NOI18N
        btnAgregarM.setMinimumSize(new java.awt.Dimension(92, 22));
        btnAgregarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMActionPerformed(evt);
            }
        });

        btnModifM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_edit_16px.png"))); // NOI18N
        btnModifM.setEnabled(false);
        btnModifM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifMActionPerformed(evt);
            }
        });

        btnUnidMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_add_16px.png"))); // NOI18N
        btnUnidMed.setEnabled(false);
        btnUnidMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidMedActionPerformed(evt);
            }
        });

        btnElimM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_trash_16px.png"))); // NOI18N
        btnElimM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMedidasLayout = new javax.swing.GroupLayout(pnlMedidas);
        pnlMedidas.setLayout(pnlMedidasLayout);
        pnlMedidasLayout.setHorizontalGroup(
            pnlMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedidasLayout.createSequentialGroup()
                        .addGroup(pnlMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedida)
                            .addComponent(lblCant))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlMedidasLayout.createSequentialGroup()
                        .addGroup(pnlMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scpMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtMedida)
                            .addGroup(pnlMedidasLayout.createSequentialGroup()
                                .addComponent(txtCant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbUnidadMedida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUnidMed, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMedidasLayout.createSequentialGroup()
                                .addComponent(btnAgregarM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModifM, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnElimM, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        pnlMedidasLayout.setVerticalGroup(
            pnlMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMedida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMedidasLayout.createSequentialGroup()
                        .addGroup(pnlMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUnidMed)
                            .addGroup(pnlMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifM, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(btnElimM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpMedidas, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlImagenes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Galería", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_back_16px.png"))); // NOI18N
        btnAnterior.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        pnlImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlImagenLayout = new javax.swing.GroupLayout(pnlImagen);
        pnlImagen.setLayout(pnlImagenLayout);
        pnlImagenLayout.setHorizontalGroup(
            pnlImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        pnlImagenLayout.setVerticalGroup(
            pnlImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        btnSiguiente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setText("1/10");

        btnAgregar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_plus_math_16px.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnVerGaleria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnVerGaleria.setText("Galería");
        btnVerGaleria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerGaleriaActionPerformed(evt);
            }
        });

        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_multiply_16px.png"))); // NOI18N
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlImagenesLayout = new javax.swing.GroupLayout(pnlImagenes);
        pnlImagenes.setLayout(pnlImagenesLayout);
        pnlImagenesLayout.setHorizontalGroup(
            pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagenesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlImagenesLayout.createSequentialGroup()
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImagenesLayout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerGaleria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitar)))
                .addContainerGap())
        );
        pnlImagenesLayout.setVerticalGroup(
            pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagenesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVerGaleria, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMaquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMedidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlImagenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMedidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlMaquinas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnNuevoMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoMaquinaActionPerformed
        maquinaAction("new");
    }//GEN-LAST:event_btnNuevoMaquinaActionPerformed

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        maquinaAction("edit");
        if (!txtCodigo.equals("")) {
            btnModifM.setEnabled(true);
        }
    }//GEN-LAST:event_btnModifActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void rdbNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbNombreMouseClicked

    }//GEN-LAST:event_rdbNombreMouseClicked

    private void rdbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNombreActionPerformed

    }//GEN-LAST:event_rdbNombreActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        //UtilVista.cargarTablaStock(cp.getCstock().traerProductos(), tblStock);


    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        getValores();

        switch (action) {
            case "new":
                if (nombre.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "No puede haber campos vacíos", "Advertencia", HEIGHT);
                    txtNombre.requestFocus();
                } else {
                    try {
                        Maquinas maquina = cp.getCs().newMaquina(nombre, cod);

                        List<Medidas> medidas = new ArrayList<Medidas>();

                        if (tblMedidas.getRowCount() > 0) {
                            for (int i = 0; i < tblMedidas.getRowCount(); i++) {
                                String nomMedida = String.valueOf(tblMedidas.getValueAt(i, 0));
                                String cant = String.valueOf(tblMedidas.getValueAt(i, 1));
                                UnidadDeMedida um = cp.getCs().findUnidadDeMedidaNombre(String.valueOf(tblMedidas.getValueAt(i, 2)));

                                cp.getCs().newMedidas(nomMedida, cant, maquina, um);
                            }
                        }

                        JOptionPane.showMessageDialog(null, "La Máquina se registró con éxito ", "¡Éxito!", HEIGHT);
                        initState();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                }
                break;
            case "edit":
                /*
                if (tblCliente.getSelectedRow() > -1 && tblCliente.getSelectedRowCount() == 1) {
                    int seleccionado = (int) tblCliente.getValueAt(tblCliente.getSelectedRow(), 0);
                    if (nombre.isEmpty() || apellido.isEmpty() || dni.isEmpty() || cel.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "No puede haber campos vacíos", "Advertencia", HEIGHT);
                        txtNombre.requestFocus();
                    } else {
                        try {
                            cp.getCc().editCliente(seleccionado, nombre, apellido, dni,
                                    tel, cel, correo, mercadoLibre, olx, ig, fb);
                            JOptionPane.showMessageDialog(null, "El Cliente se modificó con éxito", "¡Éxito!", HEIGHT);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                        }
                    }
                }
                 */
                break;
            default:
                break;
        }
        initState();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnVerGaleriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerGaleriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerGaleriaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        jdialogSelectorImg selector = new jdialogSelectorImg(vp, true);
        selector.show();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancel();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rdbCODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbCODMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCODMouseClicked

    private void rdbCODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCODActionPerformed

    private void cmbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBajaActionPerformed

    private void cmbUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUnidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUnidadMedidaActionPerformed

    private void txtCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantActionPerformed

    private void btnModifMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifMActionPerformed

    }//GEN-LAST:event_btnModifMActionPerformed

    private void btnAgregarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMActionPerformed
        if (txtMedida.getText().isEmpty() || txtCant.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No puede haber campos vacíos");
            txtMedida.requestFocus();
        } else {
            DefaultTableModel dtm = (DefaultTableModel) tblMedidas.getModel();
            Object fila[] = new Object[3];
            fila[0] = txtMedida.getText();
            fila[1] = txtCant.getText();
            fila[2] = cmbUnidadMedida.getSelectedItem();

            dtm.addRow(fila);

            txtMedida.setText("");
            txtCant.setText("");
        }
    }//GEN-LAST:event_btnAgregarMActionPerformed

    private void btnUnidMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidMedActionPerformed
        jdialogUnidadMedida um = new jdialogUnidadMedida(vp, true, cp, this, true);
        um.show();
    }//GEN-LAST:event_btnUnidMedActionPerformed

    private void btnElimMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimMActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblMedidas.getModel();
        if (action != "edit") {
            if (tblMedidas.getSelectedRow() > -1 && tblMedidas.getSelectedRowCount() == 1) {
                dtm.removeRow(tblMedidas.getSelectedRow());
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un elemento de la Tabla Medidas");
            }
        } else {
            try {
                if (tblMedidas.getSelectedRow() > -1 && tblMedidas.getSelectedRowCount() == 1) {
                    int seleccionado = (int) tblMedidas.getValueAt(tblMedidas.getSelectedRow(), 0);
                    cp.getCs().destroyMedidas(seleccionado);
                    Maquinas maquina = cp.getCs().findMaquinaCod(txtCodigo.getText());
                    if (cp.getCs().findAllMedidasMaquina(maquina.getId()).equals(null)) {
                        btnModifM.setEnabled(false);
                    }
                    UtilVista.cargarTablaMedidas(cp.getCs().findAllMedidasMaquina(maquina.getId()), tblMedidas);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnElimMActionPerformed

    private void tblMaquinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaquinasMouseClicked
        if (tblMaquinas.getSelectedRow() > -1 && tblMaquinas.getSelectedRowCount() == 1) {
            String seleccionado = (String) tblMaquinas.getValueAt(tblMaquinas.getSelectedRow(), 0);
            Maquinas maquina = this.cp.getCs().findMaquinaCod(seleccionado);
            if (maquina != null) {
                cancel();
                btnModif.setEnabled(true);
                btnEliminar.setEnabled(true);
                txtNombre.setText(maquina.getNombre());
                txtCodigo.setText(maquina.getCod());
                //txtaDescip.setText(maquina.getDescripcion());

                UtilVista.cargarTablaMedidas(cp.getCs().findAllMedidasMaquina(maquina.getId()), tblMedidas);

            } else {
                JOptionPane.showMessageDialog(null, "Error al traer los datos. El Cliente no existe", "Error", HEIGHT);
            }
        }
    }//GEN-LAST:event_tblMaquinasMouseClicked

    private void tblMedidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedidasMouseClicked
        if (!txtCodigo.getText().isEmpty()) {
            Maquinas maquina = cp.getCs().findMaquinaCod(txtCodigo.getText());
            if (!maquina.equals(null)) {
                if (tblMedidas.getSelectedRow() > -1 && tblMedidas.getSelectedRowCount() == 1) {
                    int seleccionado = (int) tblMedidas.getValueAt(tblMedidas.getSelectedRow(), 0);
                    Medidas medida = this.cp.getCs().findMedidas(seleccionado);
                    if (medida != null) {
                        txtMedida.setText(medida.getNombre());
                        txtCant.setText(medida.getCantidad());
                        UnidadDeMedida um = cp.getCs().findUnidadDeMedida(medida.getUnidadDeMedida().getId());
                        cmbUnidadMedida.getModel().setSelectedItem(um);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al traer los datos. El Cliente no existe", "Error", HEIGHT);
                    }
                }
            } else {
                txtMedida.setText((String) tblMedidas.getValueAt(tblMedidas.getSelectedRow(), 0));
                txtCant.setText((String) tblMedidas.getValueAt(tblMedidas.getSelectedRow(), 1));
                UnidadDeMedida um = cp.getCs().findUnidadDeMedidaNombre((String) tblMedidas.getValueAt(tblMedidas.getSelectedRow(), 2));
                cmbUnidadMedida.getModel().setSelectedItem(um);
            }
        }
    }//GEN-LAST:event_tblMedidasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarM;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnElimM;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModif;
    private javax.swing.JButton btnModifM;
    private javax.swing.JButton btnNuevoMaquina;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnTodos;
    private javax.swing.JButton btnUnidMed;
    private javax.swing.JButton btnVerGaleria;
    private javax.swing.JComboBox<String> cmbBaja;
    public javax.swing.JComboBox<Object> cmbUnidadMedida;
    private javax.swing.JLabel lblCant;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescrip;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMedida;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlImagen;
    private javax.swing.JPanel pnlImagenes;
    private javax.swing.JPanel pnlMaquinas;
    private javax.swing.JPanel pnlMedidas;
    private javax.swing.JRadioButton rdbCOD;
    private javax.swing.JRadioButton rdbNombre;
    private javax.swing.JScrollPane scpDescrip;
    private javax.swing.JScrollPane scpMaquinas;
    private javax.swing.JScrollPane scpMedidas;
    private javax.swing.JTable tblMaquinas;
    private javax.swing.JTable tblMedidas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMedida;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtaDescip;
    // End of variables declaration//GEN-END:variables
}
